# Generated by Django 4.2.2 on 2023-10-30 22:25

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='expense',
            field=django_cryptography.fields.encrypt(models.FloatField()),
        ),
    ]
