# Generated by Django 4.2.2 on 2023-09-28 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_maincategory_user_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'M'), ('other', 'X'), ('female', 'F')], default='M', max_length=6),
        ),
    ]
