# Generated by Django 4.2.2 on 2023-09-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_dob_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'M'), ('other', 'X'), ('female', 'F')], default='M', max_length=6),
        ),
    ]
