# Generated by Django 4.2.2 on 2023-09-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_maincategory_user_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'M'), ('female', 'F'), ('other', 'X')], default='M', max_length=6),
        ),
    ]
