# Generated by Django 4.2.2 on 2023-09-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dob',
            new_name='dateOfBirth',
        ),
    ]
