# Generated by Django 4.2.2 on 2023-09-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='main_category',
            new_name='main_category_ref',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'M'), ('other', 'X'), ('female', 'F')], default='M', max_length=6),
        ),
    ]
