# Generated by Django 4.2.2 on 2023-09-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_main_category_subcategory_main_category_ref_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='main_category_ref',
            new_name='main_category',
        ),
    ]
