# Generated by Django 4.2.2 on 2023-10-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'M'), ('female', 'F'), ('other', 'X')], default='M', max_length=6),
        ),
    ]
