services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped
    networks:
      - goldnest

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3
      - SECRET_KEY=1234
      - ENCRYPTION_KEY=2Pm1eJudARlg6x0l4QxxH9F4ESzXnHVxvYeIpuDzmp0=
      - DEBUG=True
    restart: unless-stopped
    networks:
      - goldnest

networks:
  goldnest:
    driver: bridge
