POST http://127.0.0.1:8000/api/signup 
Content-Type: application/json

{ 
    "username": "corey", 
    "password": "Pass1234!", 
    "email": "corey@mail.com" 
}

###

POST http://127.0.0.1:8000/api/login 
Content-Type: application/json

{ 
    "username": "corey", 
    "password": "Pass1234!" 
}

###

GET http://127.0.0.1:8000/api/test_token 
Content-Type: application/json 
Authorization: Token 856930c7572c73b08ac792000a3286fc5b895148